<?php

/**
 * @file
 * Demonstration functionality for the Spark distribution.
 */

// == Layouts =================================================================

/**
 * Implementation of hook_ctools_plugin_api().
 *
 * Tell CTools that we support the panels default layouts API.
 */
function spark_demo_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels' && $api == 'layouts') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_default_panels_layout().
 *
 * Provide a default layout for demonstration.
 */
function spark_demo_default_panels_layout() {
  $export = array();

  $layout = new stdClass();
  $layout->disabled = FALSE; /* Edit this to true to make a default layout disabled initially */
  $layout->api_version = 1;
  $layout->name = 'spark_demo_home';
  $layout->admin_title = 'Spark demo home';
  $layout->admin_description = '';
  $layout->category = '';
  $layout->plugin = 'responsive';
  $layout->settings = array(
    'regions' => array(
      'header_a' => 'header_a',
      'header_b' => 'header_b',
      'header_c' => 'header_c',
      'subheader_a' => 'subheader_a',
      'subheader_b' => 'subheader_b',
      'subheader_c' => 'subheader_c',
      'navigation' => 'navigation',
      'title' => 'title',
      'sidebar_a' => 'sidebar_a',
      'body' => 'body',
      'sidebar_b' => 'sidebar_b',
      'footer_a' => 'footer_a',
      'footer_b' => 'footer_b',
      'footer_c' => 'footer_c',
    ),
    'overrides' => array(
      'smartphone' => array(),
      'tablet' => array(
        0 => array(
          'name' => 'header_a',
          'columns' => 2,
        ),
        1 => array(
          'name' => 'header_b',
          'columns' => 2,
        ),
        2 => array(
          'name' => 'header_c',
          'columns' => 2,
        ),
        3 => array(
          'name' => 'subheader_a',
          'columns' => 2,
        ),
        4 => array(
          'name' => 'subheader_b',
          'columns' => 2,
        ),
        5 => array(
          'name' => 'subheader_c',
          'columns' => 2,
        ),
        6 => array(
          'name' => 'body',
          'columns' => 4,
        ),
        7 => array(
          'name' => 'sidebar_a',
          'columns' => 1,
        ),
        8 => array(
          'name' => 'sidebar_b',
          'columns' => 1,
        ),
        9 => array(
          'name' => 'footer_a',
          'columns' => 2,
        ),
        10 => array(
          'name' => 'footer_b',
          'columns' => 2,
        ),
        11 => array(
          'name' => 'footer_c',
          'columns' => 2,
        ),
      ),
      'standard' => array(
        0 => array(
          'name' => 'header_a',
          'columns' => 6,
        ),
        1 => array(
          'name' => 'header_b',
          'columns' => 3,
        ),
        2 => array(
          'name' => 'header_c',
          'columns' => 3,
        ),
        3 => array(
          'name' => 'subheader_a',
          'columns' => 4,
        ),
        4 => array(
          'name' => 'subheader_b',
          'columns' => 4,
        ),
        5 => array(
          'name' => 'subheader_c',
          'columns' => 4,
        ),
        6 => array(
          'name' => 'body',
          'columns' => 7,
        ),
        7 => array(
          'name' => 'sidebar_a',
          'columns' => 3,
        ),
        8 => array(
          'name' => 'sidebar_b',
          'columns' => 2,
        ),
        9 => array(
          'name' => 'footer_a',
          'columns' => 4,
        ),
        10 => array(
          'name' => 'footer_b',
          'columns' => 4,
        ),
        11 => array(
          'name' => 'footer_c',
          'columns' => 4,
        ),
      ),
    ),
  );
  $export['spark_demo_home'] = $layout;

  return $export;
}
